import { apiRequest, ApiError } from '../api-client';

export { ApiError };

export type ActivityStatus = 'PENDIENTE' | 'HECHA' | 'CANCELADA';
export type EntityType = 'LEAD' | 'CLIENT' | 'OPPORTUNITY';

export interface Activity {
  tenantId: string;
  activityId: string;
  userId: string;
  createdByUserId: string;
  assignedToUserId: string;
  entityType?: EntityType | null;
  entityId?: string | null;
  entityType_entityId?: string | null;
  clientId?: string | null;
  tipoCodigo: string;
  status: ActivityStatus;
  dueDate: string;
  scheduledAt?: string | null;
  reminderAt?: string | null;
  notes?: string | null;
  outcomes?: string[] | null;
  checklist?: Array<{ text: string; done: boolean }> | null;
  autoGenerated?: boolean;
  completedAt?: string | null;
  cancelledAt?: string | null;
  createdAt: string;
  updatedAt: string;
  // Enriched fields from API
  tipoLabel?: string;
  entityName?: string;
}

export interface TodayResponse {
  atrasadas: Activity[];
  hoy: Activity[];
  estaSemana: Activity[];
  counts: {
    atrasadas: number;
    hoy: number;
    estaSemana: number;
  };
}

export interface CreateActivityData {
  tipoCodigo: string;
  dueDate: string;
  entityType?: EntityType;
  entityId?: string;
  clientId?: string;
  scheduledAt?: string;
  reminderAt?: string;
  notes?: string;
  outcomes?: string[];
  checklist?: Array<{ text: string; done: boolean }>;
  assignedToUserId?: string;
  autoGenerated?: boolean;
}

export interface PatchActivityData {
  tipoCodigo?: string;
  dueDate?: string;
  scheduledAt?: string | null;
  reminderAt?: string | null;
  notes?: string | null;
  outcomes?: string[] | null;
  checklist?: Array<{ text: string; done: boolean }> | null;
  assignedToUserId?: string;
  entityType?: EntityType;
  entityId?: string;
  clientId?: string;
}

export interface ActivityListParams {
  status?: string;
  dateFrom?: string;
  dateTo?: string;
  entityType?: string;
  view?: 'agenda';
  search?: string;
  limit?: number;
  nextToken?: string;
}

export interface ActivityListResponse {
  activities: Activity[];
  count: number;
  nextToken?: string;
}

export interface RescheduleData {
  mode: '+2h' | 'tomorrow_10am' | 'custom';
  customDate?: string;
  customTime?: string;
}

export const activitiesApi = {
  async list(params?: ActivityListParams): Promise<ActivityListResponse> {
    const query = new URLSearchParams();
    if (params?.status) query.set('status', params.status);
    if (params?.dateFrom) query.set('dateFrom', params.dateFrom);
    if (params?.dateTo) query.set('dateTo', params.dateTo);
    if (params?.entityType) query.set('entityType', params.entityType);
    if (params?.view) query.set('view', params.view);
    if (params?.search) query.set('search', params.search);
    if (params?.limit !== undefined) query.set('limit', String(params.limit));
    if (params?.nextToken) query.set('nextToken', params.nextToken);
    const qs = query.toString();
    return apiRequest<ActivityListResponse>(`/activities${qs ? `?${qs}` : ''}`);
  },

  async getToday(): Promise<TodayResponse> {
    return apiRequest<TodayResponse>('/activities/today');
  },

  async get(id: string): Promise<Activity> {
    return apiRequest<Activity>(`/activities/${id}`);
  },

  async create(data: CreateActivityData): Promise<{ activity: Activity; created: boolean }> {
    return apiRequest<{ activity: Activity; created: boolean }>('/activities', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  },

  async patch(id: string, data: PatchActivityData): Promise<Activity> {
    return apiRequest<Activity>(`/activities/${id}`, {
      method: 'PATCH',
      body: JSON.stringify(data),
    });
  },

  async complete(id: string, body?: { outcomes?: string[]; notes?: string }): Promise<Activity> {
    return apiRequest<Activity>(`/activities/${id}/complete`, {
      method: 'POST',
      body: JSON.stringify(body ?? {}),
    });
  },

  async cancel(id: string): Promise<Activity> {
    return apiRequest<Activity>(`/activities/${id}/cancel`, {
      method: 'POST',
      body: JSON.stringify({}),
    });
  },

  async reschedule(id: string, data: RescheduleData): Promise<Activity> {
    return apiRequest<Activity>(`/activities/${id}/reschedule`, {
      method: 'POST',
      body: JSON.stringify(data),
    });
  },

  async delete(id: string): Promise<{ success: boolean }> {
    return apiRequest<{ success: boolean }>(`/activities/${id}`, {
      method: 'DELETE',
    });
  },

  async getByEntity(entityType: string, entityId: string): Promise<ActivityListResponse> {
    return apiRequest<ActivityListResponse>(`/activities/by-entity/${entityType}/${entityId}`);
  },

  async getAgenda(dateFrom: string, dateTo: string): Promise<ActivityListResponse> {
    const query = new URLSearchParams();
    query.set('view', 'agenda');
    query.set('dateFrom', dateFrom);
    query.set('dateTo', dateTo);
    query.set('status', 'PENDIENTE');
    return apiRequest<ActivityListResponse>(`/activities?${query.toString()}`);
  },
};
