"""
Shared auto-activity creation with anti-spam protection.
Used by lead-handler, opportunity-handler, and renewal-checker to create
activities automatically without duplicating existing pending ones.
"""
from __future__ import annotations

import json
import os
import uuid
import logging
from datetime import datetime, timezone

import boto3
from boto3.dynamodb.conditions import Key, Attr

logger = logging.getLogger(__name__)

_dynamodb = None


def get_dynamodb():
    global _dynamodb
    if _dynamodb is None:
        _dynamodb = boto3.resource("dynamodb", region_name="us-east-1")
    return _dynamodb


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def create_auto_activity(
    activities_table: str,
    tenant_id: str,
    user_id: str,
    tipo_codigo: str,
    due_date: str,
    entity_type: str | None = None,
    entity_id: str | None = None,
    client_id: str | None = None,
    notes: str | None = None,
    scheduled_at: str | None = None,
) -> dict | None:
    """
    Create an auto-generated activity with anti-spam protection.

    Anti-spam rule: At most ONE open auto-generated activity per
    (tenantId, entityType, entityId, tipoCodigo). Checked via entity-index GSI.

    Returns the created activity dict, or None if blocked by anti-spam.
    """
    table = get_dynamodb().Table(activities_table)

    # Build composite entity key
    entity_composite = None
    if entity_type and entity_id:
        entity_composite = f"{entity_type}#{entity_id}"

        # Anti-spam: check for existing PENDIENTE + autoGenerated + same tipoCodigo
        try:
            result = table.query(
                IndexName="entity-index",
                KeyConditionExpression=Key("entityType_entityId").eq(entity_composite),
                FilterExpression=(
                    Attr("status").eq("PENDIENTE")
                    & Attr("autoGenerated").eq(True)
                    & Attr("tipoCodigo").eq(tipo_codigo)
                ),
                Limit=1,
            )
            if result.get("Items"):
                existing = result["Items"][0]
                logger.info(
                    "Anti-spam: blocked duplicate auto-activity %s for %s (existing: %s)",
                    tipo_codigo,
                    entity_composite,
                    existing.get("activityId"),
                )
                return None
        except Exception as e:
            logger.warning("Anti-spam check failed (proceeding with creation): %s", e)

    now = now_iso()
    activity_id = str(uuid.uuid4())

    item: dict = {
        "tenantId": tenant_id,
        "activityId": activity_id,
        "userId": user_id,
        "createdByUserId": user_id,
        "assignedToUserId": user_id,
        "tipoCodigo": tipo_codigo,
        "status": "PENDIENTE",
        "dueDate": due_date,
        "autoGenerated": True,
        "createdAt": now,
        "updatedAt": now,
    }

    if entity_type:
        item["entityType"] = entity_type
    if entity_id:
        item["entityId"] = entity_id
    if entity_composite:
        item["entityType_entityId"] = entity_composite
    if client_id:
        item["clientId"] = client_id
    if notes:
        item["notes"] = notes
    if scheduled_at:
        item["scheduledAt"] = scheduled_at

    # Remove None sparse fields
    for field in list(item.keys()):
        if item[field] is None:
            del item[field]

    table.put_item(Item=item)
    logger.info(
        "Auto-activity created: activityId=%s tipoCodigo=%s entity=%s",
        activity_id,
        tipo_codigo,
        entity_composite,
    )
    return item
